apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: NodePort
  ports:
  - name: webui
    port: 8081
    targetPort: 8081
    nodePort: 30911
    protocol: TCP
  - name: rpc
    port: 6123
    targetPort: 6123
    protocol: TCP 
  - name: blob-server
    port: 6124
    targetPort: 6124
    protocol: TCP
  selector:
    app: flink
    component: jobmanager